name = "tic-tac-toe-do"
main = "src/index.ts"
compatibility_date = "2026-03-20"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "TicTacToe"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TicTacToe"]

routes = [
  { pattern = "tictactoe.ksanthoshkumar.com/*", custom_domain = true }
]
